name: "CHANGELOG.md 📝"
# https://github.com/TriPSs/conventional-changelog-action

on:
  push:
    branches: [ "develop", "release/**" ]
  workflow_dispatch:

jobs:
  changelog:
    name: Conventional Changelog 📝
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      # Create CHANGELOG.md
      - name: Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          git-message: 'chore(release): {version}'
          git-user-name: '${{ github.actor }}'
          git-user-email: '${{ github.actor }}@users.noreply.github.com'
          release-count: 0
          version-file: ./project.json
          version-path: gameVersion
          skip-on-empty: false
          git-branch: develop