name: CI

on:
  push:
    branches: [ "master", "develop", "feature/**", "releases/**" ]
  pull_request:
    branches: [ "master", "develop", "feature/**", "releases/**" ]
  workflow_dispatch:

jobs:
  build:
    name: PSScriptAnalyzer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run PSScriptAnalyzer
      uses: devblackops/github-action-psscriptanalyzer@master
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
