name: "CI: Unity Test ✅"

on:
  workflow_dispatch: {}
#on:
#  push:
#    branches: [ "develop", "release/**" ]

jobs:
  test:
    name: ${{ matrix.dir }} Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir:
          - Server
          - Client
        targetPlatform:
          - StandaloneWindows64
          - StandaloneLinux64
          - StandaloneOSX
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: ${{ matrix.dir }}/Library
          key: Library-${{ matrix.dir }}
          restore-keys: Library-

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ${{ matrix.dir }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Test Results
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: ${{ steps.tests.outputs.artifactsPath }}

      # Code Coverage
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Coverage results
          path: ${{ steps.tests.outputs.coveragePath }}